### ISSUE TITLE
UInexpected keyword argument 'verbose'

### ISSUE THREAD

**Issue by DaveHoskins** [koiava/Image2Shadertoy#1]
Error when run, I checked everything is installed to the latest.

```
C:\Users\[name]\Desktop\Image2Shadertoy-main\Image2Shadertoy>python Image2Shadertoy.py -i neo.png -n 32
Using device: cpu
Warning: CUDA not available, running on CPU
Initial number of Gaussians: 32
Starting stage 1: 32 total Gaussians, 2000 iterations
Traceback (most recent call last):
  File "C:\Users\[name]\Desktop\Image2Shadertoy-main\Image2Shadertoy\Image2Shadertoy.py", line 490, in <module>
    main()
    ~~~~^^
  File "C:\Users\[name]Desktop\Image2Shadertoy-main\Image2Shadertoy\Image2Shadertoy.py", line 414, in main
    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=100, min_lr=1e-6, verbose=True)
TypeError: ReduceLROnPlateau.__init__() got an unexpected keyword argument 'verbose'
```

**Comment by koiava** [comment]
This disn't appeared on a GPU for some reason. I fixed it now I think. Runs fine now on my machine, but running it on a CPU is very slow. I really recomment getting pytorch with cuda.

**Comment by DaveHoskins** [comment]
Wow that was quick. Thanks, no errors now. 
Aslo, I didn't realise it needed a separate verion of pytorch for Cuda.

This site helped: https://discuss.pytorch.org/t/help-with-install-torch-with-cuda/211985
It's currently at stage 2, and my GPUs fans are going fast.
